/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.records;


import io.skai.accounting.jooq.tables.Client;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mobile_accounting.client.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mobile_accounting.client.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mobile_accounting.client.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mobile_accounting.client.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mobile_accounting.client.email</code>. Renamed column
     * email
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mobile_accounting.client.email</code>. Renamed column
     * email
     */
    public String getEmail() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Client.CLIENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Client.CLIENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Client.CLIENT.EMAIL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public ClientRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ClientRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ClientRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public ClientRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Long id, String name, String email) {
        super(Client.CLIENT);

        setId(id);
        setName(name);
        setEmail(email);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(io.skai.accounting.jooq.tables.pojos.Client value) {
        super(Client.CLIENT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
        }
    }
}
