/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.records;


import io.skai.accounting.jooq.tables.Delivery;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryRecord extends UpdatableRecordImpl<DeliveryRecord> implements Record6<Long, LocalDateTime, Long, Long, Double, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mobile_accounting.delivery.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mobile_accounting.delivery.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mobile_accounting.delivery.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>mobile_accounting.delivery.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>mobile_accounting.delivery.order_id</code>.
     */
    public void setOrderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>mobile_accounting.delivery.order_id</code>.
     */
    public Long getOrderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>mobile_accounting.delivery.manager_id</code>.
     */
    public void setManagerId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>mobile_accounting.delivery.manager_id</code>.
     */
    public Long getManagerId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>mobile_accounting.delivery.sum</code>.
     */
    public void setSum(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>mobile_accounting.delivery.sum</code>.
     */
    public Double getSum() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>mobile_accounting.delivery.guid</code>.
     */
    public void setGuid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mobile_accounting.delivery.guid</code>.
     */
    public String getGuid() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, LocalDateTime, Long, Long, Double, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, LocalDateTime, Long, Long, Double, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Delivery.DELIVERY.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Delivery.DELIVERY.DATE;
    }

    @Override
    public Field<Long> field3() {
        return Delivery.DELIVERY.ORDER_ID;
    }

    @Override
    public Field<Long> field4() {
        return Delivery.DELIVERY.MANAGER_ID;
    }

    @Override
    public Field<Double> field5() {
        return Delivery.DELIVERY.SUM;
    }

    @Override
    public Field<String> field6() {
        return Delivery.DELIVERY.GUID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getDate();
    }

    @Override
    public Long component3() {
        return getOrderId();
    }

    @Override
    public Long component4() {
        return getManagerId();
    }

    @Override
    public Double component5() {
        return getSum();
    }

    @Override
    public String component6() {
        return getGuid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getDate();
    }

    @Override
    public Long value3() {
        return getOrderId();
    }

    @Override
    public Long value4() {
        return getManagerId();
    }

    @Override
    public Double value5() {
        return getSum();
    }

    @Override
    public String value6() {
        return getGuid();
    }

    @Override
    public DeliveryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DeliveryRecord value2(LocalDateTime value) {
        setDate(value);
        return this;
    }

    @Override
    public DeliveryRecord value3(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public DeliveryRecord value4(Long value) {
        setManagerId(value);
        return this;
    }

    @Override
    public DeliveryRecord value5(Double value) {
        setSum(value);
        return this;
    }

    @Override
    public DeliveryRecord value6(String value) {
        setGuid(value);
        return this;
    }

    @Override
    public DeliveryRecord values(Long value1, LocalDateTime value2, Long value3, Long value4, Double value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeliveryRecord
     */
    public DeliveryRecord() {
        super(Delivery.DELIVERY);
    }

    /**
     * Create a detached, initialised DeliveryRecord
     */
    public DeliveryRecord(Long id, LocalDateTime date, Long orderId, Long managerId, Double sum, String guid) {
        super(Delivery.DELIVERY);

        setId(id);
        setDate(date);
        setOrderId(orderId);
        setManagerId(managerId);
        setSum(sum);
        setGuid(guid);
    }

    /**
     * Create a detached, initialised DeliveryRecord
     */
    public DeliveryRecord(io.skai.accounting.jooq.tables.pojos.Delivery value) {
        super(Delivery.DELIVERY);

        if (value != null) {
            setId(value.getId());
            setDate(value.getDate());
            setOrderId(value.getOrderId());
            setManagerId(value.getManagerId());
            setSum(value.getSum());
            setGuid(value.getGuid());
        }
    }
}
