/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.records;


import io.skai.accounting.jooq.tables.Order;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record6<Long, Long, Long, String, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mobile_accounting.order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mobile_accounting.order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mobile_accounting.order.client_id</code>.
     */
    public void setClientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mobile_accounting.order.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mobile_accounting.order.model_id</code>.
     */
    public void setModelId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>mobile_accounting.order.model_id</code>.
     */
    public Long getModelId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>mobile_accounting.order.serial_number</code>.
     */
    public void setSerialNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mobile_accounting.order.serial_number</code>.
     */
    public String getSerialNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mobile_accounting.order.defect</code>.
     */
    public void setDefect(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mobile_accounting.order.defect</code>.
     */
    public String getDefect() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mobile_accounting.order.manager_id</code>.
     */
    public void setManagerId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>mobile_accounting.order.manager_id</code>.
     */
    public Long getManagerId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, String, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Order.ORDER.ID;
    }

    @Override
    public Field<Long> field2() {
        return Order.ORDER.CLIENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return Order.ORDER.MODEL_ID;
    }

    @Override
    public Field<String> field4() {
        return Order.ORDER.SERIAL_NUMBER;
    }

    @Override
    public Field<String> field5() {
        return Order.ORDER.DEFECT;
    }

    @Override
    public Field<Long> field6() {
        return Order.ORDER.MANAGER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getClientId();
    }

    @Override
    public Long component3() {
        return getModelId();
    }

    @Override
    public String component4() {
        return getSerialNumber();
    }

    @Override
    public String component5() {
        return getDefect();
    }

    @Override
    public Long component6() {
        return getManagerId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getClientId();
    }

    @Override
    public Long value3() {
        return getModelId();
    }

    @Override
    public String value4() {
        return getSerialNumber();
    }

    @Override
    public String value5() {
        return getDefect();
    }

    @Override
    public Long value6() {
        return getManagerId();
    }

    @Override
    public OrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public OrderRecord value2(Long value) {
        setClientId(value);
        return this;
    }

    @Override
    public OrderRecord value3(Long value) {
        setModelId(value);
        return this;
    }

    @Override
    public OrderRecord value4(String value) {
        setSerialNumber(value);
        return this;
    }

    @Override
    public OrderRecord value5(String value) {
        setDefect(value);
        return this;
    }

    @Override
    public OrderRecord value6(Long value) {
        setManagerId(value);
        return this;
    }

    @Override
    public OrderRecord values(Long value1, Long value2, Long value3, String value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Long id, Long clientId, Long modelId, String serialNumber, String defect, Long managerId) {
        super(Order.ORDER);

        setId(id);
        setClientId(clientId);
        setModelId(modelId);
        setSerialNumber(serialNumber);
        setDefect(defect);
        setManagerId(managerId);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(io.skai.accounting.jooq.tables.pojos.Order value) {
        super(Order.ORDER);

        if (value != null) {
            setId(value.getId());
            setClientId(value.getClientId());
            setModelId(value.getModelId());
            setSerialNumber(value.getSerialNumber());
            setDefect(value.getDefect());
            setManagerId(value.getManagerId());
        }
    }
}
