/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Client implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String email;

    public Client() {}

    public Client(Client value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
    }

    public Client(
        Long   id,
        String name,
        String email
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    /**
     * Getter for <code>mobile_accounting.client.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>mobile_accounting.client.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>mobile_accounting.client.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>mobile_accounting.client.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>mobile_accounting.client.email</code>. Renamed column
     * email
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>mobile_accounting.client.email</code>. Renamed column
     * email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Client (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
