/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Delivery implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime date;
    private Long          orderId;
    private Long          managerId;
    private Double        sum;
    private String        guid;

    public Delivery() {}

    public Delivery(Delivery value) {
        this.id = value.id;
        this.date = value.date;
        this.orderId = value.orderId;
        this.managerId = value.managerId;
        this.sum = value.sum;
        this.guid = value.guid;
    }

    public Delivery(
        Long          id,
        LocalDateTime date,
        Long          orderId,
        Long          managerId,
        Double        sum,
        String        guid
    ) {
        this.id = id;
        this.date = date;
        this.orderId = orderId;
        this.managerId = managerId;
        this.sum = sum;
        this.guid = guid;
    }

    /**
     * Getter for <code>mobile_accounting.delivery.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>mobile_accounting.delivery.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>mobile_accounting.delivery.date</code>.
     */
    public LocalDateTime getDate() {
        return this.date;
    }

    /**
     * Setter for <code>mobile_accounting.delivery.date</code>.
     */
    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * Getter for <code>mobile_accounting.delivery.order_id</code>.
     */
    public Long getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>mobile_accounting.delivery.order_id</code>.
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>mobile_accounting.delivery.manager_id</code>.
     */
    public Long getManagerId() {
        return this.managerId;
    }

    /**
     * Setter for <code>mobile_accounting.delivery.manager_id</code>.
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * Getter for <code>mobile_accounting.delivery.sum</code>.
     */
    public Double getSum() {
        return this.sum;
    }

    /**
     * Setter for <code>mobile_accounting.delivery.sum</code>.
     */
    public void setSum(Double sum) {
        this.sum = sum;
    }

    /**
     * Getter for <code>mobile_accounting.delivery.guid</code>.
     */
    public String getGuid() {
        return this.guid;
    }

    /**
     * Setter for <code>mobile_accounting.delivery.guid</code>.
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Delivery (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(orderId);
        sb.append(", ").append(managerId);
        sb.append(", ").append(sum);
        sb.append(", ").append(guid);

        sb.append(")");
        return sb.toString();
    }
}
