/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Model implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   brandId;
    private String name;

    public Model() {}

    public Model(Model value) {
        this.id = value.id;
        this.brandId = value.brandId;
        this.name = value.name;
    }

    public Model(
        Long   id,
        Long   brandId,
        String name
    ) {
        this.id = id;
        this.brandId = brandId;
        this.name = name;
    }

    /**
     * Getter for <code>mobile_accounting.model.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>mobile_accounting.model.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>mobile_accounting.model.brand_id</code>.
     */
    public Long getBrandId() {
        return this.brandId;
    }

    /**
     * Setter for <code>mobile_accounting.model.brand_id</code>.
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * Getter for <code>mobile_accounting.model.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>mobile_accounting.model.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Model (");

        sb.append(id);
        sb.append(", ").append(brandId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
