/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Model implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long brandId;
    private String name;

    public Model() {}

    public Model(Model value) {
        this.id = value.id;
        this.brandId = value.brandId;
        this.name = value.name;
    }

    public Model(
        Long id,
        Long brandId,
        String name
    ) {
        this.id = id;
        this.brandId = brandId;
        this.name = name;
    }

    /**
     * Getter for <code>mobile_accounting.model.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>mobile_accounting.model.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>mobile_accounting.model.brand_id</code>.
     */
    public Long getBrandId() {
        return this.brandId;
    }

    /**
     * Setter for <code>mobile_accounting.model.brand_id</code>.
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * Getter for <code>mobile_accounting.model.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>mobile_accounting.model.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Model other = (Model) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.brandId == null) {
            if (other.brandId != null)
                return false;
        }
        else if (!this.brandId.equals(other.brandId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.brandId == null) ? 0 : this.brandId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Model (");

        sb.append(id);
        sb.append(", ").append(brandId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
