/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private String  name;
    private String  email;
    private String  phone;
    private String  password;
    private Integer role;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
        this.phone = value.phone;
        this.password = value.password;
        this.role = value.role;
    }

    public User(
        Long    id,
        String  name,
        String  email,
        String  phone,
        String  password,
        Integer role
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.role = role;
    }

    /**
     * Getter for <code>mobile_accounting.user.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>mobile_accounting.user.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>mobile_accounting.user.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>mobile_accounting.user.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>mobile_accounting.user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>mobile_accounting.user.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>mobile_accounting.user.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>mobile_accounting.user.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>mobile_accounting.user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>mobile_accounting.user.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>mobile_accounting.user.role</code>.
     */
    public Integer getRole() {
        return this.role;
    }

    /**
     * Setter for <code>mobile_accounting.user.role</code>.
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(password);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
