server:
  port: 8081

springdoc:
  swagger-ui:
    path: swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: art.tkach@gmail.com
    password: olfsbvftoktxwecy
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
