server:
  port: 8081

springdoc:
  swagger-ui:
    path: swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    username: artem
    password: 12345
    url: jdbc:mysql://localhost:3309/mobile_notifications?createDatabaseIfNotExist=TRUE&currentSchema=mobile_notifications
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:config.liquibase/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: art.tkach@gmail.com
    password: olfsbvftoktxwecy
    protocol: smtp
    smtp-auth: true
  kafka:
    topic-name: orderNotification
    group-id: notification
    consumer:
      group-id: notification
    bootstrap-servers: localhost:29092