/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq;


import io.skai.accounting.jooq.tables.Brand;
import io.skai.accounting.jooq.tables.Client;
import io.skai.accounting.jooq.tables.Delivery;
import io.skai.accounting.jooq.tables.Model;
import io.skai.accounting.jooq.tables.Order;
import io.skai.accounting.jooq.tables.OrderStatus;
import io.skai.accounting.jooq.tables.Repair;
import io.skai.accounting.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MobileAccounting extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mobile_accounting</code>
     */
    public static final MobileAccounting MOBILE_ACCOUNTING = new MobileAccounting();

    /**
     * The table <code>mobile_accounting.brand</code>.
     */
    public final Brand BRAND = Brand.BRAND;

    /**
     * The table <code>mobile_accounting.client</code>.
     */
    public final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>mobile_accounting.delivery</code>.
     */
    public final Delivery DELIVERY = Delivery.DELIVERY;

    /**
     * The table <code>mobile_accounting.model</code>.
     */
    public final Model MODEL = Model.MODEL;

    /**
     * The table <code>mobile_accounting.order</code>.
     */
    public final Order ORDER = Order.ORDER;

    /**
     * The table <code>mobile_accounting.order_status</code>.
     */
    public final OrderStatus ORDER_STATUS = OrderStatus.ORDER_STATUS;

    /**
     * The table <code>mobile_accounting.repair</code>.
     */
    public final Repair REPAIR = Repair.REPAIR;

    /**
     * The table <code>mobile_accounting.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private MobileAccounting() {
        super("mobile_accounting", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Brand.BRAND,
            Client.CLIENT,
            Delivery.DELIVERY,
            Model.MODEL,
            Order.ORDER,
            OrderStatus.ORDER_STATUS,
            Repair.REPAIR,
            User.USER
        );
    }
}
