/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq;


import io.skai.accounting.jooq.tables.Brand;
import io.skai.accounting.jooq.tables.Client;
import io.skai.accounting.jooq.tables.Model;
import io.skai.accounting.jooq.tables.Order;
import io.skai.accounting.jooq.tables.OrderStatus;
import io.skai.accounting.jooq.tables.Repair;
import io.skai.accounting.jooq.tables.User;


/**
 * Convenience access to all tables in mobile_accounting.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mobile_accounting.brand</code>.
     */
    public static final Brand BRAND = Brand.BRAND;

    /**
     * The table <code>mobile_accounting.client</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>mobile_accounting.model</code>.
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * The table <code>mobile_accounting.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>mobile_accounting.order_status</code>.
     */
    public static final OrderStatus ORDER_STATUS = OrderStatus.ORDER_STATUS;

    /**
     * The table <code>mobile_accounting.repair</code>.
     */
    public static final Repair REPAIR = Repair.REPAIR;

    /**
     * The table <code>mobile_accounting.user</code>.
     */
    public static final User USER = User.USER;
}
