/*
 * This file is generated by jOOQ.
 */
package io.skai.accounting.jooq.tables;


import io.skai.accounting.jooq.Keys;
import io.skai.accounting.jooq.MobileAccounting;
import io.skai.accounting.jooq.tables.records.DeliveryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Delivery extends TableImpl<DeliveryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mobile_accounting.delivery</code>
     */
    public static final Delivery DELIVERY = new Delivery();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeliveryRecord> getRecordType() {
        return DeliveryRecord.class;
    }

    /**
     * The column <code>mobile_accounting.delivery.id</code>.
     */
    public final TableField<DeliveryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>mobile_accounting.delivery.date</code>.
     */
    public final TableField<DeliveryRecord, LocalDateTime> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>mobile_accounting.delivery.order_id</code>.
     */
    public final TableField<DeliveryRecord, Long> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>mobile_accounting.delivery.manager_id</code>.
     */
    public final TableField<DeliveryRecord, Long> MANAGER_ID = createField(DSL.name("manager_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>mobile_accounting.delivery.sum</code>.
     */
    public final TableField<DeliveryRecord, Double> SUM = createField(DSL.name("sum"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>mobile_accounting.delivery.guid</code>.
     */
    public final TableField<DeliveryRecord, String> GUID = createField(DSL.name("guid"), SQLDataType.VARCHAR(68).nullable(false), this, "");

    private Delivery(Name alias, Table<DeliveryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Delivery(Name alias, Table<DeliveryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mobile_accounting.delivery</code> table reference
     */
    public Delivery(String alias) {
        this(DSL.name(alias), DELIVERY);
    }

    /**
     * Create an aliased <code>mobile_accounting.delivery</code> table reference
     */
    public Delivery(Name alias) {
        this(alias, DELIVERY);
    }

    /**
     * Create a <code>mobile_accounting.delivery</code> table reference
     */
    public Delivery() {
        this(DSL.name("delivery"), null);
    }

    public <O extends Record> Delivery(Table<O> child, ForeignKey<O, DeliveryRecord> key) {
        super(child, key, DELIVERY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MobileAccounting.MOBILE_ACCOUNTING;
    }

    @Override
    public Identity<DeliveryRecord, Long> getIdentity() {
        return (Identity<DeliveryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DeliveryRecord> getPrimaryKey() {
        return Keys.KEY_DELIVERY_PRIMARY;
    }

    @Override
    public List<UniqueKey<DeliveryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_DELIVERY_GUID);
    }

    @Override
    public List<ForeignKey<DeliveryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DELIVERY_MANAGER_USER);
    }

    private transient User _user;

    /**
     * Get the implicit join path to the <code>mobile_accounting.user</code>
     * table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.FK_DELIVERY_MANAGER_USER);

        return _user;
    }

    @Override
    public Delivery as(String alias) {
        return new Delivery(DSL.name(alias), this);
    }

    @Override
    public Delivery as(Name alias) {
        return new Delivery(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Delivery rename(String name) {
        return new Delivery(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Delivery rename(Name name) {
        return new Delivery(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, LocalDateTime, Long, Long, Double, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
