server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:29092
  cache:
    type: redis
    redis:
      time-to-live: 43200000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3307/mobile_accounting?createDatabaseIfNotExist=TRUE&currentSchema=mobile_accounting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: artem
    password: 12345

  application:
    name: md
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  data:
    redis:
      port: 6379
      host: localhost

springdoc:
  swagger-ui:
    path: /swagger-ui.html