server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3307/mobile_accounting?createDatabaseIfNotExist=TRUE&currentSchema=mobile_accounting
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: md
  liquibase:
    change-log: classpath:config/liquibase/master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
